/* ==============================================================
   Road Trip Californie 2026 — Données planning v16
   23 juillet – 16 août 2026 · 24 jours · 23 nuits
   ============================================================== */


const DAYS = [
  { num:"J1", date:"Jeu 23 juil", title:"San Francisco (nuit 1/3)",
    activities:[
      { time:"13h50", type:"activity", label:"🏃 Activité", desc:"🏨 [Jour d'arrivée — pas de départ d'hôtel ce jour] — Atterrissage SFO. Bagages + immigration.", dur:"~1h" },
      { time:"15h00", type:"car", label:"🚗 Voiture", desc:"SFO → Royal Pacific · 661 Broadway, San Francisco CA 94133 (Airbnb · petit déjeuner inclus)", dur:"45 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Voiture garée au parking hôtel — n'en bouge plus jusqu'au Jour 4 après-midi.", dur:"" },
      { time:"16h00", type:"activity", label:"🏃 Activité", desc:"Check-in hôtel. Repos — décalage 9h Paris → SF.", dur:"" },
      { time:"16h30", type:"walk", label:"🚶 À pied", desc:"Union Square : place centrale de SF, grands magasins, sculptures.", dur:"30 min" },
      { time:"17h05", type:"transit", label:"🚌 Muni", desc:"Union Square → Embarcadero", dur:"10 min" },
      { time:"17h20", type:"walk", label:"🚶 À pied", desc:"Hyatt Regency SF (5 Embarcadero Center) : atrium spectaculaire 17 étages. Entrée libre.", dur:"20 min" },
      { time:"17h45", type:"walk", label:"🚶 À pied", desc:"Hyatt Regency → Pier 39 (Fisherman's Wharf)", dur:"10 min" },
      { time:"18h00", type:"walk", label:"🚶 À pied", desc:"Pier 39 : lions de mer, boutiques, ambiance du port.", dur:"45 min" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Fisherman's Wharf : fruits de mer, chowder en pain sourdough.", dur:"1h" },
      { time:"21h00", type:"alert", label:"⚠️ Alerte", desc:"Coucher tôt obligatoire — récupération jet-lag 9h de décalage.", dur:"" }
    ]
  },
  { num:"J2", date:"Ven 24 juil", title:"Vélo Golden Gate + Sausalito (ferry) · Quartiers SF",
    activities:[
      { time:"08h45", type:"bike", label:"🚲 Location vélo", desc:"🏨 [Départ hôtel Royal Pacific ~08h20, ~20-25 min à pied] — Unlimited Biking, 757 Beach Street (près de Ghirardelli Square) — casque + antivol + billet ferry inclus. Vélo électrique recommandé (montées sportives). Réservez en ligne à l'avance.", dur:"~$35/pers" },
      { time:"09h00", type:"bike", label:"🚲 Vélo", desc:"Sentiers du Presidio à vélo : forêt d'eucalyptus, vues sur la baie.", dur:"25 min" },
      { time:"09h30", type:"walk", label:"🚶 À pied", desc:"Palace of Fine Arts : rotonde romaine au bord d'un lac. Arrêt photo.", dur:"15 min" },
      { time:"09h50", type:"bike", label:"🚲 Vélo", desc:"Fort Point : fort sous le tablier du Golden Gate. Selfie sous le pont depuis le bas — perspective unique.", dur:"20 min" },
      { time:"10h15", type:"walk", label:"🚶 À pied", desc:"Torpedo Wharf : vue frontale sur le Golden Gate avant la traversée.", dur:"10 min" },
      { time:"10h30", type:"bike", label:"🚲 Vélo", desc:"Traversée Golden Gate Bridge à vélo (gratuit). 2,7 km, vue à 360° sur la baie, Alcatraz, la skyline.", dur:"30 min" },
      { time:"11h05", type:"walk", label:"🚶 À pied", desc:"Vista Point + Golden Gate Recreation Area (côté Marin) : meilleur point de vue du Golden Gate.", dur:"20 min" },
      { time:"11h30", type:"bike", label:"🚲 Vélo", desc:"Descente vers Sausalito (15 min, route en lacets — facile en électrique).", dur:"15 min" },
      { time:"11h50", type:"walk", label:"🚶 À pied", desc:"Sausalito : port de pêcheur, marina, boutiques. Houseboats (maisons flottantes) dans le port.", dur:"40 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Sausalito — terrasse face à la baie, fruits de mer locaux", dur:"1h" },
      { time:"13h30", type:"boat", label:"⛴ Ferry", desc:"Ferry Blue & Gold Fleet : Sausalito → Fisherman's Wharf avec les vélos (billet inclus). Vue sur Alcatraz et la skyline de SF.", dur:"30 min" },
      { time:"14h00", type:"bike", label:"🚲 Vélo", desc:"Retour au loueur Unlimited Biking. Restitution des vélos.", dur:"15 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Vêtement chaud obligatoire — il fait ~15°C sur le pont même en juillet.", dur:"" },
      { time:"14h20", type:"transit", label:"🚌 Cable car Powell-Hyde", desc:"Fisherman's Wharf → Nob Hill : grandes demeures victoriennes, Grace Cathedral, Huntington Park.", dur:"20 min · inclus pass" },
      { time:"14h45", type:"walk", label:"🚶 À pied", desc:"Russian Hill : quartier bohème, jardins cachés, vues sur la baie.", dur:"15 min" },
      { time:"15h05", type:"walk", label:"🚶 À pied", desc:"Lombard Street : descente à pied du célèbre zigzag à 8 virages.", dur:"20 min" },
      { time:"15h30", type:"walk", label:"🚶 À pied", desc:"Filbert Street : rue la plus pentue de SF, perroquets sauvages.", dur:"15 min" },
      { time:"15h50", type:"walk", label:"🚶 À pied", desc:"Chinatown : Grant Avenue, temples, épiceries exotiques.", dur:"45 min" },
      { time:"16h40", type:"walk", label:"🚶 À pied", desc:"Bank of California Building (400 California St) : architecture néo-classique 1908.", dur:"15 min" },
      { time:"17h00", type:"transit", label:"🚌 Ligne F (tramway historique)", desc:"Financial District → Civic Center via Market Street. Tramways vintage années 1930–50.", dur:"20 min · inclus pass" },
      { time:"17h25", type:"walk", label:"🚶 À pied", desc:"Civic Center : City Hall (dôme doré 1915), Bill Graham Civic Auditorium, architecture Beaux-Arts.", dur:"25 min" },
      { time:"17h55", type:"transit", label:"🚌 Muni bus 21", desc:"Civic Center → Alamo Square", dur:"15 min" },
      { time:"18h15", type:"walk", label:"🚶 À pied", desc:"Painted Ladies (Alamo Square) : photo face à la skyline de SF au coucher de soleil.", dur:"20 min" },
      { time:"18h40", type:"transit", label:"🚌 Muni", desc:"Alamo Square → hôtel", dur:"15 min" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner SF — Hayes Valley ou Mission District.", dur:"1h" }
    ]
  },
  { num:"J3", date:"Sam 25 juil", title:"Battery Spencer · Twin Peaks · Coit Tower · SoMa · Ferry Building",
    activities:[
      { time:"09h00", type:"activity", label:"🏃 Activité", desc:"Départ hôtel en voiture — seule demi-journée en voiture à SF.", dur:"" },
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"Hôtel → Battery Spencer (traversée Golden Gate Bridge, côté Marin)", dur:"20 min" },
      { time:"09h25", type:"walk", label:"🚶 À pied", desc:"Battery Spencer : photo emblématique du Golden Gate en surplomb depuis les fortifications militaires.", dur:"20 min" },
      { time:"09h50", type:"car", label:"🚗 Voiture", desc:"Battery Spencer → Twin Peaks (retour côté SF)", dur:"25 min" },
      { time:"10h15", type:"walk", label:"🚶 À pied", desc:"Twin Peaks : vue à 360° sur toute SF depuis 280m. La meilleure vue panoramique de la ville.", dur:"30 min" },
      { time:"10h50", type:"car", label:"🚗 Voiture", desc:"Twin Peaks → Coit Tower (North Beach)", dur:"15 min" },
      { time:"11h05", type:"parking", label:"🅿 Parking", desc:"Coit Tower Lot (Telegraph Hill Blvd) — arrivez tôt, places limitées.", dur:"$5–8/h" },
      { time:"11h10", type:"walk", label:"🚶 À pied", desc:"Coit Tower : fresques murales New Deal (années 30) + vue panoramique sur la baie et Alcatraz.", dur:"40 min" },
      { time:"11h55", type:"car", label:"🚗 Voiture", desc:"Coit Tower → parking hôtel. Voiture rendue — pas reprise de l'après-midi.", dur:"10 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — North Beach — Tony's Pizza, Café Vesuvio ou Mama's", dur:"1h" },
      { time:"13h30", type:"activity", label:"🚌 Ligne F", desc:"Hôtel → SoMa via Market Street", dur:"15 min · inclus pass" },
      { time:"13h50", type:"walk", label:"🚶 À pied", desc:"SoMa : galeries d'art contemporain, street art, architecture industrielle reconvertie.", dur:"30 min" },
      { time:"14h25", type:"activity", label:"🚌 Ligne F (suite)", desc:"SoMa → Embarcadero (Ferry Building)", dur:"10 min · inclus pass" },
      { time:"14h40", type:"walk", label:"🚶 À pied", desc:"Ferry Building Marketplace : marché producteurs, huîtres Hog Island, chocolat Dandelion, café Blue Bottle.", dur:"1h" },
      { time:"15h45", type:"walk", label:"🚶 À pied", desc:"Embarcadero : promenade baie, vue Bay Bridge et Alcatraz.", dur:"30 min" },
      { time:"16h20", type:"transit", label:"🚌 Muni", desc:"Embarcadero → hôtel", dur:"15 min" },
      { time:"16h40", type:"activity", label:"🏃 Activité", desc:"Retour hôtel. Repos. Préparer bagages — départ Yosemite demain après le déjeuner.", dur:"" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dernier grand dîner SF.", dur:"1h" }
    ]
  },
  { num:"J4", date:"Dim 26 juil", title:"Haight · Castro · Columbia Gold Rush → Yosemite West",
    activities:[
      { time:"09h00", type:"activity", label:"🏃 Activité", desc:"Petit-déjeuner hôtel. Bagages bouclés et prêts — check-out avant de partir visiter.", dur:"" },
      { time:"09h30", type:"transit", label:"🚌 Muni", desc:"🏨 [Départ hôtel Royal Pacific ~09h20] — Hôtel → Haight-Ashbury", dur:"20 min" },
      { time:"09h55", type:"walk", label:"🚶 À pied", desc:"Haight-Ashbury : berceau du mouvement hippie, boutiques vintage, murales psychédéliques.", dur:"40 min" },
      { time:"10h40", type:"transit", label:"🚌 Muni bus 24", desc:"Haight-Ashbury → Castro District", dur:"10 min" },
      { time:"10h55", type:"walk", label:"🚶 À pied", desc:"Castro : Rainbow Flag, architecture victorienne colorée, boutiques emblématiques.", dur:"30 min" },
      { time:"11h30", type:"walk", label:"🚶 À pied", desc:"Maison bleue (3841 18th Street) : maison victorienne emblématique du Castro. Photo.", dur:"10 min" },
      { time:"11h45", type:"transit", label:"🚌 Muni", desc:"Castro → hôtel (récupérer bagages et voiture)", dur:"20 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Près de l'hôtel — déjeuner rapide avant la route", dur:"1h" },
      { time:"13h30", type:"car", label:"🚗 Voiture", desc:"SF → Columbia State Historic Park via I-580 + Hwy 120 — 220 km (corrigé, était 145 km)", dur:"2h45" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Columbia est sur la Hwy 49 près de Sonora. Entrée et parking gratuits. Activités ouvertes 10h–17h en été.", dur:"" },
      { time:"16h15", type:"walk", label:"🚶 À pied", desc:"Columbia State Historic Park : ville Gold Rush 1850 parfaitement préservée. Guides en costumes d'époque, pan for gold (chercher de l'or), balade en diligence, blacksmith, saloons, boutiques d'époque. Plus grande collection de bâtiments Gold Rush de Californie.", dur:"1h30" },
      { time:"17h45", type:"car", label:"🚗 Voiture", desc:"Columbia → Yosemite West (Henness Circle) via Hwy 108 + Hwy 120 + Hwy 41 — 105 km", dur:"1h50" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Entrée dans le parc par Big Oak Flat (Hwy 120). Puis Hwy 41 direction sud jusqu'au panneau Yosemite West. America the Beautiful Pass requis à l'entrée.", dur:"" },
      { time:"19h35", type:"activity", label:"🏃 Activité", desc:"Arrivée condo B104 — 7540 Henness Circle #B104, Yosemite West CA 95389 (Airbnb · petit déjeuner inclus)", dur:"" },
      { time:"20h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner au condo (provisions achetées à Sonora avant Columbia) ou Wawona Hotel restaurant (15 min voiture).", dur:"1h" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Aucun restaurant à Yosemite West. Faites provisions à Sonora ou Columbia avant d'entrer dans le parc. Wawona Hotel à 15 min. ⚠️ Arrivée révisée ~19h35 (trajet réel plus long que prévu) — prévoir un dîner froid/simple au condo.", dur:"" }
    ]
  },
  { num:"J5", date:"Lun 27 juil", title:"Glacier Point (matin) + Mist Trail Vernal & Nevada Fall (après-midi)",
    activities:[
      { time:"07h10", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Condo Yosemite West 07h10] — Condo Yosemite West → Glacier Point via Glacier Point Road (juste à côté du condo !) — ⚠️ Départ tôt volontaire : pour le lever de soleil sur Half Dome à Glacier Point ET pour trouver une place au parking, complet dès 9h30 en été.", dur:"10 min" },
      { time:"07h20", type:"parking", label:"🅿 Parking", desc:"Glacier Point Lot — arrivez tôt (complet dès 9h30 en été).", dur:"Gratuit (pass)" },
      { time:"07h25", type:"walk", label:"🚶 À pied", desc:"Glacier Point (2200m) : vue absolue sur Half Dome, Nevada Fall et la vallée 1000m plus bas. La plus belle vue de Yosemite. Lever de soleil magique.", dur:"1h" },
      { time:"08h30", type:"car", label:"🚗 Voiture", desc:"Glacier Point → parking Day Use Valley via Hwy 41 + Hwy 140", dur:"30 min" },
      { time:"09h00", type:"parking", label:"🅿 Parking", desc:"Day Use Valley — inclus America the Beautiful Pass.", dur:"Gratuit (pass)" },
      { time:"09h10", type:"transit", label:"🚌 Navette gratuite", desc:"Arrêt Village → Arrêt 16 (Happy Isles, départ Mist Trail)", dur:"15 min" },
      { time:"09h25", type:"walk", label:"🚶 Mist Trail complet", desc:"Départ Happy Isles → Vernal Fall (97m, embruns puissants — imperméable obligatoire) → continuation John Muir Trail → Nevada Fall (180m). Descente via John Muir Trail (variante sèche). Total : ~11 km A/R, +600m.", dur:"4h30" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Imperméable OBLIGATOIRE dès l'approche de Vernal Fall — embruns qui trempent complètement.", dur:"" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Yosemite Village — Village Store ou Valley Lodge", dur:"1h" },
      { time:"13h30", type:"walk", label:"🚶 À pied", desc:"Valley Visitor Center + Ansel Adams Gallery.", dur:"45 min" },
      { time:"14h20", type:"walk", label:"🚶 À pied", desc:"Rives Merced River — vue El Capitan et Half Dome. Balade libre.", dur:"40 min" },
      { time:"15h00", type:"car", label:"🚗 Voiture", desc:"Parking Day Use Valley → condo Yosemite West via Hwy 41", dur:"20 min" },
      { time:"15h20", type:"activity", label:"🏃 Activité", desc:"Retour condo. Repos après la journée (Glacier Point + Mist Trail 4h30).", dur:"" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner au condo (provisions) ou Wawona Hotel restaurant (15 min voiture).", dur:"1h" }
    ]
  },
  { num:"J6", date:"Mar 28 juil", title:"Yosemite Falls (matin) + Mirror Lake + balade vallée (après-midi)",
    activities:[
      { time:"07h00", type:"activity", label:"🏃 Activité", desc:"Lever 7h00. Petit-déjeuner au condo. Pique-nique + 2L eau/pers. — ⚠️ Lever tôt volontaire : le Yosemite Falls Trail (11 km, +650m, 3h30) est exposé au soleil sans ombre — mieux vaut le faire tôt, avant la chaleur et la foule.", dur:"" },
      { time:"07h30", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Condo Yosemite West 07h30] — Condo Yosemite West → parking Day Use Valley", dur:"20 min" },
      { time:"07h50", type:"parking", label:"🅿 Parking", desc:"Day Use Valley — inclus America the Beautiful Pass.", dur:"Gratuit (pass)" },
      { time:"08h00", type:"transit", label:"🚌 Navette gratuite", desc:"Arrêt Village → Arrêt 6 (Yosemite Falls Trailhead, côté nord de la vallée)", dur:"10 min" },
      { time:"08h10", type:"walk", label:"🚶 À pied", desc:"Yosemite Falls Trail : 11 km A/R, +650m. Plus haute chute d'Amérique du Nord (739m). Vue depuis le sommet sur toute la vallée.", dur:"3h30" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Yosemite Village — déjeuner après la randonnée", dur:"1h" },
      { time:"13h30", type:"walk", label:"🚶 À pied", desc:"Mirror Lake Trail : 5 km à pied plat. Vue sur Half Dome. (En août lac à demi sec mais balade belle.)", dur:"1h30" },
      { time:"15h05", type:"walk", label:"🚶 À pied", desc:"Balade libre : rives Merced River, vue El Capitan. Possibilité vélo de vallée.", dur:"1h" },
      { time:"16h10", type:"car", label:"🚗 Voiture", desc:"Parking Day Use Valley → condo Yosemite West", dur:"20 min" },
      { time:"16h35", type:"activity", label:"🏃 Activité", desc:"Retour condo. Repos. Préparer bagages Kings Canyon.", dur:"" },
      { time:"17h00", type:"activity", label:"🧺 Lessive", desc:"Lessive au condo (lave-linge sur place) — profitez-en avant la route vers Kings Canyon demain.", dur:"1h30" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner au condo (provisions) ou Wawona Hotel restaurant (15 min voiture).", dur:"1h" }
    ]
  },
  { num:"J7", date:"Mer 29 juil", title:"Olmsted Point + Tenaya Lake + Tuolumne → Mariposa Grove → Fresno → Kings Canyon",
    activities:[
      { time:"06h30", type:"alert", label:"⚠️ Alerte", desc:"LEVER 6h30 — grande journée de transition vers Kings Canyon. Départ tôt indispensable.", dur:"" },
      { time:"06h30", type:"activity", label:"🏃 Activité", desc:"Petit-déjeuner. Pique-nique + eau. Check-out condo Yosemite West. Bagages en voiture.", dur:"" },
      { time:"07h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Condo Yosemite West 07h00] — Condo Yosemite West → Olmsted Point via Hwy 41 + Hwy 120 (Tioga Road) — 50 km", dur:"1h" },
      { time:"08h00", type:"walk", label:"🚶 À pied", desc:"Olmsted Point : vue nord sur Half Dome depuis Tioga Road. Granite poli par les glaciers.", dur:"30 min" },
      { time:"08h35", type:"car", label:"🚗 Voiture", desc:"Olmsted Point → Tenaya Lake", dur:"10 min" },
      { time:"08h45", type:"walk", label:"🚶 À pied", desc:"Tenaya Lake (2484m) : lac glaciaire turquoise. Baignade possible (~15°C). Pique-nique sur les berges.", dur:"45 min" },
      { time:"09h35", type:"car", label:"🚗 Voiture", desc:"Tenaya Lake → Tuolumne Meadows", dur:"20 min" },
      { time:"09h55", type:"walk", label:"🚶 À pied", desc:"Tuolumne Meadows : prairie alpine à 2600m. Lembert Dome Trail (3 km A/R).", dur:"2h" },
      { time:"12h00", type:"car", label:"🚗 Voiture", desc:"Tuolumne Meadows → Mariposa Grove via Big Oak Flat Road + Hwy 41 — 130 km (corrigé, était 75 km)", dur:"2h20" },
      { time:"13h00", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — provisions voiture ou Wawona Hotel (en chemin)", dur:"1h" },
      { time:"15h20", type:"parking", label:"🅿 Parking", desc:"South Entrance Mariposa Grove Lot", dur:"Gratuit (pass)" },
      { time:"15h25", type:"transit", label:"🚌 Navette obligatoire", desc:"Parking → Mariposa Grove (pas d'accès voiture direct en saison)", dur:"5 min" },
      { time:"15h30", type:"walk", label:"🚶 À pied", desc:"Mariposa Grove : Grizzly Giant (2700 ans, 63m), California Tunnel Tree, Big Trees Loop.", dur:"1h30" },
      { time:"17h00", type:"car", label:"🚗 Voiture", desc:"Mariposa Grove → Fresno via Hwy 41 — 90 km", dur:"1h30" },
      { time:"18h30", type:"activity", label:"🏃 Activité", desc:"Fresno : plein d'essence + provisions supermarché.", dur:"20 min" },
      { time:"18h50", type:"car", label:"🚗 Voiture", desc:"Fresno → Gena's Sierra Inn (Dunlap, Kings Canyon) via Hwy 180 — 45 km", dur:"40 min" },
      { time:"19h30", type:"activity", label:"🏃 Activité", desc:"Check-in Gena's Sierra Inn & Bella Brooke Cafe — 37692 East Kings Canyon Rd, Dunlap CA 93621 (Booking · ⚠️ petit déjeuner NON inclus)", dur:"" },
      { time:"20h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Bella Brooke Cafe (sur place à Gena's Sierra Inn).", dur:"1h" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Zumwalt Meadow Trail (3 km A/R) reporté au lendemain matin pour alléger cette journée de transition. ⚠️ Journée révisée : trajet Tuolumne→Mariposa Grove réellement ~2h20 (et non 1h30) — départ de Tuolumne Meadows à 12h00 à ne pas retarder. Le trajet Fresno → Gena's Sierra Inn (~45 km / 40 min via Hwy 180) permet d'arriver au check-in vers 19h30.", dur:"" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Hébergement Kings Canyon très limité — réservez sur recreation.gov le plus tôt possible.", dur:"" }
    ]
  },
  { num:"J8", date:"Jeu 30 juil", title:"Zumwalt Meadow Trail + Sequoia NP → Three Rivers",
    activities:[
      { time:"07h30", type:"activity", label:"🏃 Activité", desc:"Petit-déjeuner avec les provisions achetées à Fresno la veille (petit déjeuner NON inclus à Gena's Sierra Inn). Pique-nique + eau.", dur:"" },
      { time:"08h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Gena's Sierra Inn 08h00] — Lodge → Zumwalt Meadow (Cedar Grove, Kings Canyon)", dur:"10 min" },
      { time:"08h10", type:"walk", label:"🚶 À pied", desc:"Zumwalt Meadow Trail : 3 km A/R. Prairie au fond du canyon, parois granitiques à 1500m au-dessus. L'un des plus beaux panoramas de Kings Canyon. Frais et calme le matin.", dur:"1h" },
      { time:"09h15", type:"car", label:"🚗 Voiture", desc:"Zumwalt Meadow → Kings Canyon → Generals Highway → Sequoia NP (Giant Forest)", dur:"45 min" },
      { time:"10h00", type:"transit", label:"🚌 Navette Wuksachi", desc:"Wuksachi Lodge → General Sherman Tree (navette obligatoire en saison)", dur:"5 min" },
      { time:"10h05", type:"walk", label:"🚶 À pied", desc:"General Sherman Tree : le plus grand arbre du monde en volume (1385 m³). Big Tree Trail boucle 2 km autour des séquoias géants.", dur:"1h" },
      { time:"11h10", type:"car", label:"🚗 Voiture", desc:"Giant Forest → Tunnel Log", dur:"10 min" },
      { time:"11h20", type:"walk", label:"🚶 À pied", desc:"Tunnel Log : séquoia tombé en 1937, tunnel creusé dans le tronc. Photo insolite.", dur:"15 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Giant Forest — pique-nique avant la montée Moro Rock", dur:"1h" },
      { time:"13h15", type:"car", label:"🚗 Voiture", desc:"Tunnel Log → Moro Rock", dur:"10 min" },
      { time:"13h25", type:"walk", label:"🚶 À pied", desc:"Moro Rock : 300 marches, vue à 360° sur les Sierras depuis 2050m.", dur:"45 min" },
      { time:"14h15", type:"car", label:"🚗 Voiture", desc:"Moro Rock → Three Rivers via Generals Highway (sortie sud Sequoia) — 38 km", dur:"50 min" },
      { time:"15h10", type:"activity", label:"🏃 Activité", desc:"Three Rivers : plein d'essence + provisions. Achetez 4L eau/pers pour Death Valley !", dur:"30 min" },
      { time:"16h00", type:"activity", label:"🏃 Activité", desc:"Check-in Lemon Cove · 24215 Ave 324, Lemon Cove CA 93244 (Airbnb · petit déjeuner inclus). À 12 miles de Three Rivers, 25 miles entrée Sequoia.", dur:"" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner lodge.", dur:"1h" },
      { time:"", type:"tip", label:"💡 Courses", desc:"Petit déjeuner NON inclus à The Ranch At Death Valley — achetez provisions à Three Rivers ou Lemon Cove ce soir pour le lendemain matin.", dur:"30 min" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Préparez affaires Death Valley ce soir : eau abondante, vêtements légers, SPF50, chapeau.", dur:"" }
    ]
  },
  { num:"J9", date:"Ven 31 juil", title:"Three Rivers → Death Valley",
    activities:[
      { time:"07h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Lemon Cove avancé à 07h00, au lieu de 09h00] — Three Rivers → Furnace Creek (Death Valley) via Hwy 65 + Hwy 178 — 280 km (départ avancé pour arriver avant le pic de chaleur)", dur:"4h30" },
      { time:"11h30", type:"activity", label:"🏃 Activité", desc:"Arrivée Furnace Creek. Check-in The Ranch At Death Valley · Highway 190, Death Valley CA 92328. REPOS OBLIGATOIRE — ne pas sortir (jusqu'à 50°C). Piscine de l'hôtel uniquement.", dur:"" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"DEATH VALLEY AOÛT : jusqu'à 50°C. Sorties UNIQUEMENT avant 9h30 et après 19h. 4L eau/pers/jour. Ne restez jamais dans une voiture arrêtée moteur coupé. ⚠️ Départ avancé à 07h00 (au lieu de 09h00) pour arriver à 11h30 et limiter l'exposition à la chaleur pendant le trajet voiture→hôtel/check-in.", dur:"" },
      { time:"19h00", type:"car", label:"🚗 Voiture", desc:"Furnace Creek → Dante's View (1669m)", dur:"25 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Veste obligatoire à Dante's View — ~20°C en altitude même quand il fait 50°C en bas.", dur:"" },
      { time:"19h30", type:"walk", label:"🚶 À pied", desc:"Dante's View : vue panoramique sur toute la vallée et Badwater Basin. Coucher de soleil.", dur:"45 min" },
      { time:"20h20", type:"car", label:"🚗 Voiture", desc:"Dante's View → Zabriskie Point", dur:"25 min" },
      { time:"20h50", type:"walk", label:"🚶 À pied", desc:"Zabriskie Point : badlands dorés à la lumière du soir.", dur:"30 min" },
      { time:"21h25", type:"car", label:"🚗 Voiture", desc:"Zabriskie → hôtel Furnace Creek", dur:"10 min" },
      { time:"21h40", type:"meal", label:"🍽️ Dîner", desc:"Dîner tardif hôtel. Lever 5h30 demain.", dur:"1h" }
    ]
  },
  { num:"J10", date:"Sam 1er août", title:"Death Valley : dunes, Badwater, Artist Drive → Las Vegas",
    activities:[
      { time:"05h30", type:"alert", label:"⚠️ Alerte", desc:"LEVER 5h30 — fenêtre matinale avant la chaleur.", dur:"" },
      { time:"05h45", type:"walk", label:"🚶 À pied", desc:"🏨 [Sortie hôtel The Ranch At Death Valley dès 05h45 pour les dunes — check-out définitif à 09h30] — Mesquite Flat Dunes au lever du soleil. Lumière rasante dorée sur les dunes.", dur:"45 min" },
      { time:"06h30", type:"car", label:"🚗 Voiture", desc:"Mesquite Flat Dunes → Badwater Basin — 63 km (corrigé, était 20 min sans distance)", dur:"50 min" },
      { time:"07h20", type:"walk", label:"🚶 À pied", desc:"Badwater Basin : cristaux de sel, -86m, point le plus bas d'Amérique du Nord.", dur:"30 min" },
      { time:"07h50", type:"car", label:"🚗 Voiture", desc:"Badwater → Artist Drive (sens unique) — 8 km", dur:"10 min" },
      { time:"08h00", type:"walk", label:"🚶 À pied", desc:"Artist Drive : roches multicolores. Arrêt à pied à Artist's Palette.", dur:"45 min" },
      { time:"09h30", type:"activity", label:"🏃 Activité", desc:"Check-out hôtel. Terminé pour les sorties — 42°C ! (Retour Artist Drive → hôtel ~15 min + bagages inclus dans la marge jusqu'à 9h30, conformément à la règle 'sorties uniquement avant 9h30'.)", dur:"" },
      { time:"09h30", type:"car", label:"🚗 Voiture", desc:"Furnace Creek → Las Vegas via Hwy 190 + US-95 — 230 km", dur:"2h30" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — En route — pause sur US-95 (Beatty ou Amargosa Valley)", dur:"1h" },
      { time:"13h15", type:"activity", label:"🏃 Activité", desc:"Check-in Ellis Island Hotel Casino & Brewery · 4250 Koval Lane, Las Vegas NV 89109 (Booking · ⚠️ petit déjeuner NON inclus). Piscine, repos.", dur:"" },
      { time:"19h00", type:"activity", label:"🚌 Uber", desc:"Hôtel Strip → Fremont Street", dur:"15 min" },
      { time:"19h15", type:"walk", label:"🚶 À pied", desc:"Fremont Street Experience : plafond LED 460m, concerts gratuits.", dur:"1h30" },
      { time:"21h00", type:"activity", label:"🚌 Uber", desc:"Fremont → The Strip", dur:"10 min" },
      { time:"21h15", type:"walk", label:"🚶 À pied", desc:"The Strip by night : fontaines Bellagio, Caesar's Palace, MGM Grand.", dur:"2h" },
      { time:"23h15", type:"meal", label:"🍽️ Dîner", desc:"Dîner tardif sur le Strip — options ouvertes tard (buffet ou restaurant casino).", dur:"1h" }
    ]
  },
  { num:"J11", date:"Dim 2 août", title:"Las Vegas → Grand Canyon West (Hualapai Reservation) → Williams",
    activities:[
      { time:"09h00", type:"activity", label:"🏃 Activité", desc:"🏨 [Départ hôtel Ellis Island (Las Vegas) 09h00] — Check-out hôtel Las Vegas. Bagages en voiture.", dur:"" },
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"Las Vegas → Grand Canyon West Main Terminal (Hualapai Reservation) via US-93 Sud + Pierce Ferry Rd + Diamond Bar Rd — 200 km", dur:"2h30" },
      { time:"11h30", type:"activity", label:"🏃 Activité", desc:"Grand Canyon West Main Terminal : retrait des billets (All-Access Pass avec Skywalk conseillé, ~99 $/pers, sinon General Admission ~67 $/pers) et du pass navette hop-on-hop-off gratuit et illimité entre les 3 sites.", dur:"20 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Accès uniquement en navette au-delà du Main Terminal — pas de voiture particulière sur le site. Sacs et objets à déposer en casier gratuit avant le Skywalk ; téléphones/appareils photo autorisés depuis 2026. Réservez les billets à l'avance sur grandcanyonwest.com.", dur:"" },
      { time:"11h50", type:"transit", label:"🚌 Navette", desc:"Main Terminal → Hualapai Ranch", dur:"10 min" },
      { time:"12h00", type:"activity", label:"🤠 Activité", desc:"Hualapai Ranch : ambiance western, spectacle de cow-boys, balades à cheval ou en chariot (en option).", dur:"30 min" },
      { time:"12h30", type:"transit", label:"🚌 Navette", desc:"Hualapai Ranch → Eagle Point", dur:"10 min" },
      { time:"12h40", type:"walk", label:"🚶 Skywalk", desc:"Eagle Point : Skywalk (passerelle de verre en fer à cheval suspendue à 1200m au-dessus du canyon) + Native American Village (habitats traditionnels de plusieurs tribus, démonstrations culturelles).", dur:"1h30" },
      { time:"14h10", type:"transit", label:"🚌 Navette", desc:"Eagle Point → Guano Point", dur:"15 min" },
      { time:"14h25", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner sur place — stand BBQ/burgers à Guano Point.", dur:"45 min" },
      { time:"15h10", type:"walk", label:"🚶 À pied", desc:"Guano Point : point de vue le plus spectaculaire du site, vestiges du téléphérique de l'ancienne mine de guano, sentier sur la mesa à 360°.", dur:"45 min" },
      { time:"15h55", type:"transit", label:"🚌 Navette", desc:"Guano Point → Main Terminal (récupération voiture)", dur:"20 min" },
      { time:"16h15", type:"car", label:"🚗 Voiture", desc:"Grand Canyon West → Williams via Pierce Ferry Rd + US-93 Sud (Kingman) + I-40 Est — 305 km", dur:"3h20" },
      { time:"19h35", type:"activity", label:"🏃 Activité", desc:"Check-in Americas Best Value Inn · 302 East Route 66, Williams AZ 86046 (Booking · petit déjeuner inclus). Plein d'essence.", dur:"" },
      { time:"20h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Williams — Route 66.", dur:"1h" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Journée longue (départ 9h, retour hôtel ~19h35). Pas de décalage horaire entre Las Vegas et l'Arizona en août (les deux suivent l'heure d'été du Pacifique en été).", dur:"" }
    ]
  },
  { num:"J12", date:"Lun 3 août", title:"Grand Canyon South Rim (Rim Trail 5h) → Palm Springs",
    img: ["images/GrandCanyon.png", "images/GrandCanyonBus.png"],
    activities:[
      { time:"06h00", type:"activity", label:"🏃 Activité", desc:"Lever tôt — petit-déjeuner Americas Best Value Inn (inclus). Bagages en voiture, check-out.", dur:"" },
      { time:"06h30", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Americas Best Value Inn (Williams) 06h30] — Williams → Tusayan via I-40 Est + Hwy 64 Nord — 90 km", dur:"1h" },
      { time:"07h30", type:"activity", label:"🏃 Activité", desc:"Arrivée Tusayan. Garez-vous au Grand Canyon Visitor Center IMAX (450 State Route 64, Tusayan) — parking + arrêt navette violette au même endroit.", dur:"" },
      { time:"07h45", type:"transit", label:"🚌 Navette violette (Tusayan Route)", desc:"Depuis l'arrêt IMAX Tusayan → Grand Canyon Visitor Center. Toutes les 20 min (8h–21h45). Présentez l'America the Beautiful Pass — bypass de la file d'entrée.", dur:"20 min · pass" },
      { time:"08h05", type:"walk", label:"🚶 À pied", desc:"Mather Point : premier choc visuel du canyon depuis le belvédère le plus fréquenté du South Rim.", dur:"20 min" },
      { time:"08h25", type:"walk", label:"🚶 Rim Trail (vers l'ouest)", desc:"Marche Mather Point → Hermits Rest le long du Rim Trail (sentier goudronné/naturel en corniche, quasi plat) — ~20 km. Rythme tranquille, prendre son temps. Arrêts suggérés : Yavapai Point, Trailview Overlook, Maricopa Point, Powell Point, Hopi Point (meilleur panorama 180° du South Rim — à ne pas manquer), Mohave Point, The Abyss (falaise à pic 300m), Pima Point (vue sur le Colorado), puis Hermits Rest.", dur:"5h" },
      { time:"13h25", type:"transit", label:"🚌 Navette rouge (Hermits Rest Route)", desc:"Hermits Rest → Village Route Transfer (retour direct, 4 arrêts seulement : Hermits Rest, Pima, Mohave, Powell Point).", dur:"30 min · pass" },
      { time:"13h55", type:"transit", label:"🚌 Navette bleue (Village Route)", desc:"Village Route Transfer → Grand Canyon Visitor Center.", dur:"15 min · pass" },
      { time:"14h10", type:"transit", label:"🚌 Navette violette (Tusayan Route)", desc:"Grand Canyon Visitor Center → arrêt IMAX Tusayan (récupération de la voiture). Toutes les 20 min.", dur:"20 min · pass" },
      { time:"14h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner tardif à Tusayan avant la longue route vers Palm Springs.", dur:"45 min" },
      { time:"15h15", type:"car", label:"🚗 Voiture", desc:"Tusayan → Palm Springs via Hwy 64 Sud + I-40 Ouest + I-10 Est — 650 km", dur:"6h45" },
      { time:"22h00", type:"activity", label:"🏃 Activité", desc:"Check-in Caliente Tropics · 411 East Palm Canyon Drive, Palm Springs CA 92262 (Booking · ⚠️ petit déjeuner NON inclus).", dur:"" },
      { time:"22h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner tardif Palm Springs — options limitées à cette heure, prévoir repas simple ou à emporter.", dur:"" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Journée très longue (lever 6h, arrivée hôtel ~22h00) : randonnée 5h + 6h45 de route l'après-midi (avec pause essence/pause pipi incluse). Prévoir relève au volant si possible, pauses régulières et bonne hydratation. Pas de décalage horaire Arizona → Californie en été.", dur:"" }
    ]
  },
  { num:"J13", date:"Mar 4 août", title:"Joshua Tree (matin) → Palm Springs",
    activities:[
      { time:"07h00", type:"alert", label:"⚠️ Alerte", desc:"LEVER 7h00 — randonnées Joshua Tree uniquement avant 11h (40°C ensuite). Eau + chapeau + SPF50.", dur:"" },
      { time:"07h15", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Caliente Tropics 07h15] — Hôtel → West Entrance Joshua Tree National Park via Park Blvd", dur:"10 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Entrer par la West Entrance (côté Joshua Tree town) — Hidden Valley, Cap Rock et Keys View sont à l'ouest du parc. Cholla Cactus Garden est à l'est, on y passe en sortant vers Palm Springs.", dur:"" },
      { time:"07h30", type:"car", label:"🚗 Voiture", desc:"West Entrance → Hidden Valley Trailhead", dur:"25 min" },
      { time:"07h55", type:"walk", label:"🚶 À pied", desc:"Hidden Valley Trail : 1,6 km dans un cirque de granite. Site d'escalade emblématique. Vue exceptionnelle sur les Joshua Trees. Lumière du matin idéale.", dur:"45 min" },
      { time:"08h45", type:"car", label:"🚗 Voiture", desc:"Hidden Valley → Cap Rock", dur:"5 min" },
      { time:"08h50", type:"walk", label:"🚶 À pied", desc:"Cap Rock Trail : 1,6 km boucle. Formations de granite impressionnantes.", dur:"30 min" },
      { time:"09h25", type:"car", label:"🚗 Voiture", desc:"Cap Rock → Keys View (1581m)", dur:"15 min" },
      { time:"09h40", type:"walk", label:"🚶 À pied", desc:"Keys View : vue panoramique sur la vallée de Coachella, Palm Springs et la faille de San Andreas.", dur:"20 min" },
      { time:"10h05", type:"car", label:"🚗 Voiture", desc:"Keys View → Cholla Cactus Garden via Park Blvd + Pinto Basin Rd — traversée du parc vers l'est", dur:"30 min" },
      { time:"10h35", type:"walk", label:"🚶 À pied", desc:"Cholla Cactus Garden : cactus argentés translucides sur boucle de 0,4 km. Attention aux épines — ne pas toucher !", dur:"20 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner Joshua Tree town avant le départ.", dur:"1h" },
      { time:"13h30", type:"car", label:"🚗 Voiture", desc:"Joshua Tree → Palm Springs via CA-62 + Hwy 111 — 70 km", dur:"45 min" },
      { time:"14h15", type:"activity", label:"🏃 Activité", desc:"Retour à l'hôtel Caliente Tropics — piscine méritée !", dur:"1h" },
      { time:"15h30", type:"car", label:"🚗 Voiture", desc:"Hôtel → Aerial Tramway (Tramway Rd, nord ville)", dur:"10 min" },
      { time:"15h40", type:"parking", label:"🅿 Parking", desc:"Aerial Tramway Lot", dur:"Gratuit" },
      { time:"16h00", type:"walk", label:"🚶 À pied", desc:"Sommet San Jacinto : randonnée légère dans les pins, vue sur tout le désert.", dur:"45 min" },
      { time:"17h30", type:"walk", label:"🚶 À pied", desc:"Marilyn Forever (Museum Dr) : statue 11m. Photo.", dur:"15 min" },
      { time:"17h50", type:"walk", label:"🚶 À pied", desc:"Palm Canyon Drive : boutiques mid-century moderne.", dur:"30 min" },
      { time:"18h25", type:"car", label:"🚗 Voiture", desc:"Centre → Graffiti Yard (Art District)", dur:"10 min" },
      { time:"18h40", type:"walk", label:"🚶 À pied", desc:"Graffiti Yard + murales Art District + Public Art Wings.", dur:"30 min" },
      { time:"19h15", type:"car", label:"🚗 Voiture", desc:"Art District → Wash Time Coin Laundry · 1751 N Sunrise Way D1, Palm Springs — ~4 km", dur:"10 min" },
      { time:"19h25", type:"activity", label:"🧺 Lessive", desc:"Wash Time Coin Laundry · 1751 N Sunrise Way D1. Lessive complète.", dur:"2h" },
      { time:"21h25", type:"meal", label:"🍽️ Dîner", desc:"Dîner à proximité du laundromat ou à l'hôtel Caliente Tropics.", dur:"1h" }
    ]
  },
  { num:"J14", date:"Mer 5 août", title:"Palm Springs → Cimetière Westwood → Château Marmont (photo) → Venice Beach · Venice Canal · Abbot Kinney · Santa Monica",
    activities:[
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Caliente Tropics (Palm Springs) 09h00] — Palm Springs → Los Angeles via I-10 Ouest — 175 km", dur:"2h" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Sortie Bundy Dr sur I-10 pour rejoindre Wilshire Blvd direction Westwood — Cimetière Westwood est directement sur le trajet depuis l'autoroute vers Venice.", dur:"" },
      { time:"11h00", type:"parking", label:"🅿 Parking", desc:"Cimetière Westwood Village Memorial Park — entrée 1218 Glendon Ave, Los Angeles 90024. Parking dans l'allée principale.", dur:"Gratuit" },
      { time:"11h05", type:"walk", label:"🚶 À pied", desc:"Cimetière Westwood Village Memorial Park : Marilyn Monroe, Natalie Wood, Jack Lemmon, Dean Martin, Walter Matthau... Cimetière intime en plein Westwood.", dur:"30 min" },
      { time:"", type:"info", label:"🆚 Challenge", desc:"Voiture recommandée — aucune desserte Metro directe. Parking gratuit dans l'enceinte du cimetière.", dur:"" },
      { time:"11h55", type:"walk", label:"🚶 À pied", desc:"Château Marmont (8221 Sunset Blvd) : photo depuis Sunset Blvd de la façade du légendaire hôtel 1929. Arrêt rapide côté rue. Pas de parking nécessaire pour une simple photo.", dur:"10 min" },
      { time:"12h10", type:"car", label:"🚗 Voiture", desc:"Château Marmont → Venice Beach via Sunset Blvd + I-405 S + Venice Blvd — 20 min", dur:"20 min" },
      { time:"12h30", type:"parking", label:"🅿 Parking", desc:"South City Lot — Venice Beach. Garez ici toute l'après-midi : Venice Beach, Venice Canal et Abbot Kinney tous accessibles à pied.", dur:"$9 lun–ven · $18 w-e" },
      { time:"", type:"parking", label:"🅿 Adresse", desc:"2100 Ocean Front Walk, Venice CA 90291 — au bout de Venice Blvd, côté Muscle Beach/Skate Park", dur:"" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner à Venice — Abbot Kinney Blvd (15 min à pied du parking) ou Boardwalk.", dur:"1h" },
      { time:"13h30", type:"walk", label:"🚶 À pied", desc:"Venice Beach Boardwalk : skateurs, artistes de rue, Muscle Beach. 2 min à pied du parking.", dur:"45 min" },
      { time:"14h20", type:"walk", label:"🚶 À pied", desc:"Venice Canaux (Dell Avenue & Carroll Canal) : maisons colorées, ponts en bois. 10 min à pied du parking. Impossible de se garer dans ce quartier résidentiel.", dur:"35 min" },
      { time:"14h55", type:"activity", label:"🛍️ Activité", desc:"Abbot Kinney Boulevard : boutiques indépendantes, galeries, concept stores. 15 min à pied du parking.", dur:"1h" },
      { time:"16h00", type:"bike", label:"🚲 Vélo", desc:"Venice Beach → Santa Monica Pier via piste cyclable longeant l'océan (5 km). Location vélo sur le Boardwalk.", dur:"20 min · $15–20/h" },
      { time:"18h00", type:"car", label:"🚗 Voiture", desc:"Récupérer voiture → hôtel Santa Monica", dur:"20 min" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Santa Monica — Third Street Promenade ou Ocean Avenue.", dur:"1h" }
    ]
  },
  { num:"J15", date:"Jeu 6 août", title:"METRO : Griffith Observatory · Hollywood Sign · Hollyhock House · Wilshire Art Déco · Walk of Fame",
    activities:[
      { time:"", type:"tip", label:"💡 Conseil", desc:"Journée 100% Metro + DASH. Voiture à l'hôtel toute la journée. TAP Card indispensable. Budget ~$10/pers.", dur:"" },
      { time:"08h30", type:"transit", label:"🚌 Big Blue Bus", desc:"🏨 [Départ hôtel The Sea Atelier 08h30] — Hôtel Santa Monica → 7th/Metro Center", dur:"45 min · $1.25" },
      { time:"09h15", type:"transit", label:"🚇 Metro B Line", desc:"7th/Metro Center → Vermont/Sunset (direction North Hollywood) · 4 stations", dur:"10 min · $1.75" },
      { time:"09h25", type:"activity", label:"🚌 DASH Observatory", desc:"Vermont/Sunset → Griffith Observatory · toutes les 15 min · 20 min de trajet", dur:"20 min · 50¢" },
      { time:"", type:"info", label:"🆚 Challenge", desc:"Parking Griffith saturé avant 9h30 en été. Metro + DASH indispensable.", dur:"" },
      { time:"09h50", type:"walk", label:"🚶 À pied", desc:"Griffith Observatory : vue panoramique sur LA et Hollywood Sign. Expositions astronomie. Entrée gratuite.", dur:"1h" },
      { time:"10h55", type:"walk", label:"🚶 À pied", desc:"Brush Canyon Trail → Hollywood Sign : 5 km A/R depuis l'observatoire. Vue sur les lettres.", dur:"1h" },
      { time:"11h55", type:"activity", label:"🚌 DASH Observatory", desc:"Griffith Observatory → Vermont/Sunset", dur:"20 min · 50¢" },
      { time:"12h20", type:"walk", label:"🚶 À pied", desc:"Hollyhock House (Frank Lloyd Wright · UNESCO) — 4800 Hollywood Blvd · Barnsdall Art Park · visite auto-guidée jeu–sam 11h–16h · $12 adultes. Station Vermont/Sunset à 10 min à pied. Si voiture : parking Barnsdall Art Park · 4730 Barnsdall Ave · gratuit.", dur:"1h" },
      { time:"13h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner Los Feliz · Hillhurst Ave · 10 min à pied de Hollyhock House.", dur:"1h" },
      { time:"", type:"info", label:"🆚 Challenge", desc:"D Line longe tout le Miracle Mile. Metro idéal — trafic et parking très difficiles sur Wilshire Blvd.", dur:"" },
      { time:"15h00", type:"walk", label:"🚶 À pied", desc:"Wilshire Blvd Art Déco — Miracle Mile : Wiltern Theatre · Bullocks Wilshire · Academy Museum · La Brea Tar Pits · Deco Building (5209 Wilshire). Balade entre les 3 stations D Line.", dur:"1h30" },
      { time:"16h45", type:"transit", label:"🚇 Metro B Line", desc:"Wilshire/La Cienega → D Line → Wilshire/Western → B Line direction North Hollywood → Hollywood/Highland", dur:"$1.75" },
      { time:"17h10", type:"walk", label:"🚶 À pied", desc:"Walk of Fame · TCL Chinese Theatre · Dolby Theatre. Station Hollywood/Highland (B Line).", dur:"1h" },
      { time:"18h15", type:"transit", label:"🚇 Metro B Line", desc:"Hollywood/Highland → 7th/Metro Center → Big Blue Bus → hôtel Santa Monica", dur:"1h10 · ~$3" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Santa Monica — Third Street Promenade ou Ocean Avenue.", dur:"1h" }
    ]
  },
  { num:"J16", date:"Ven 7 août", title:"LA : Universal Studios (journée entière)",
    activities:[
      { time:"08h30", type:"activity", label:"🏃 Activité", desc:"Départ hôtel The Sea Atelier. Voiture garée à l'hôtel depuis J14 — reprise ce matin pour Universal Studios.", dur:"" },
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"Hôtel The Sea Atelier (Santa Monica) → Universal Studios via I-10 E + US-101 N — 35 km", dur:"30 min" },
      { time:"09h45", type:"parking", label:"🅿 Parking", desc:"Universal Studios Parking Structure", dur:"$40/jour" },
      { time:"10h00", type:"activity", label:"🏃 Activité", desc:"Ouverture Universal Studios. Wizarding World of Harry Potter en PRIORITÉ.", dur:"" },
      { time:"13h30", type:"walk", label:"🚶 À pied", desc:"Studio Tour en tram : 1h15. Coulisses, King Kong 360°, Fast & Furious, Jurassic Park.", dur:"1h15" },
      { time:"14h50", type:"walk", label:"🚶 À pied", desc:"Fast & Furious, The Mummy, Jurassic World, Transformers — attractions à volonté.", dur:"3h" },
      { time:"20h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner CityWalk à pied depuis sortie Universal.", dur:"1h" }
    ]
  },
  { num:"J17", date:"Sam 8 août", title:"VOITURE : Mulholland Drive · Runyon Canyon · Beachwood Canyon · Melrose · Spadena · Rodeo Drive",
    activities:[
      { time:"07h30", type:"activity", label:"🏃 Activité", desc:"Petit-déjeuner hôtel The Sea Atelier. Bagages bouclés, check-out.", dur:"" },
      { time:"08h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel The Sea Atelier (Santa Monica) 08h00] — Santa Monica → The Hills Inn Eagle Rock (Mount Washington) via I-10 Est + I-110 Nord — 30 km", dur:"35 min" },
      { time:"08h35", type:"activity", label:"🏃 Activité", desc:"Check-in The Hills Inn Eagle Rock · 2300 Colorado Blvd, Los Angeles CA 90041 (Airbnb · petit déjeuner inclus). Dépose des bagages, repart aussitôt pour Mulholland Drive.", dur:"" },
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"Hôtel Mount Washington → Mulholland Drive via I-110 N + US-101 N + Cahuenga Blvd — 25 min", dur:"25 min" },
      { time:"09h30", type:"parking", label:"🅿 Parking", desc:"Hollywood Bowl Overlook · 7036 Mulholland Drive · parking dédié gratuit · vue Hollywood Sign + Downtown LA", dur:"Gratuit" },
      { time:"09h35", type:"car", label:"🚗 Voiture", desc:"Mulholland Drive — Hollywood Bowl Overlook + Nancy Hoover Pohl Overlook (8401 Mulholland Dr, 40 places, gratuit) · arrêts 20 min chacun · vue San Fernando Valley", dur:"45 min" },
      { time:"", type:"info", label:"🆚 Challenge", desc:"Route panoramique en hauteur — voiture absolument obligatoire. Aucune desserte Metro ou bus.", dur:"" },
      { time:"10h25", type:"car", label:"🚗 Voiture", desc:"Mulholland → Runyon Canyon Park entrée nord via Nichols Canyon Rd + N Fuller Ave — 10 min", dur:"10 min" },
      { time:"10h35", type:"parking", label:"🅿 Parking", desc:"Entrée nord Runyon Canyon · 7317 Mulholland Drive · petit parking gratuit sur place", dur:"Gratuit" },
      { time:"10h45", type:"walk", label:"🚶 À pied", desc:"Runyon Canyon Park : 1,9 km de randonnée · vue sur Hollywood et Downtown. Très populaire avec les chiens.", dur:"1h" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Beachwood Café · 2695 N Beachwood Dr · épicerie de quartier au pied du Hollywood Sign · sandwichs artisanaux. Vue sur les lettres depuis la rue.", dur:"1h30" },
      { time:"14h05", type:"car", label:"🚗 Voiture", desc:"Beachwood Canyon → Melrose Avenue via Franklin Ave + N La Brea Ave — 15 min", dur:"15 min" },
      { time:"14h30", type:"activity", label:"🛍️ Activité", desc:"Melrose Avenue : boutiques vintage, galeries indépendantes, restaurants branchés, street art.", dur:"45 min" },
      { time:"15h20", type:"car", label:"🚗 Voiture", desc:"Melrose → Spadena House (Beverly Hills) via N Robertson Blvd + Burton Way + N Walden Dr — 10 min", dur:"10 min" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Highland Park (York Blvd) — 5 min depuis The Hills Inn Eagle Rock.", dur:"1h" }
    ]
  },
  { num:"J18", date:"Dim 9 août", title:"METRO : Highland Park · Downtown LA → Port Hueneme (Oxnard)",
    activities:[
      { time:"09h20", type:"info", label:"🏨 Hôtel", desc:"🏨 [Départ hôtel The Hills Inn Eagle Rock 09h20] — Hôtel Mount Washington — départ à pied vers la station A Line Southwest Museum (10 min, avant le Metro de 09h30).", dur:"" },
      { time:"09h30", type:"transit", label:"🚇 Metro A Line", desc:"Southwest Museum → Highland Park (Ave 57) · 1 station · 3 min", dur:"$1.75" },
      { time:"09h35", type:"activity", label:"🎨 Activité", desc:"Highland Park — York Blvd + Figueroa St : street art, galeries indépendantes, coffee shops. Sortie station Ave 57 & Figueroa — 3 min à pied de York Blvd.", dur:"1h" },
      { time:"10h40", type:"transit", label:"🚇 Metro A Line", desc:"Highland Park → Union Station · 15 min", dur:"inclus (ticket 2h)" },
      { time:"10h55", type:"transit", label:"🚇 Metro B Line", desc:"Union Station → Pershing Square · 2 stations · 4 min", dur:"inclus" },
      { time:"11h05", type:"activity", label:"🏛️ Activité", desc:"Bradbury Building · 304 S Broadway · atrium victorien 1893 · ironwork spectaculaire · connu pour Blade Runner · 4 min à pied de Pershing Square. Ouvert sam–dim 10h–17h.", dur:"30 min" },
      { time:"11h40", type:"activity", label:"🚃 Activité", desc:"Angels Flight Railway · 351 S Hill St · funiculaire historique 1901 · 298 pieds · 1 min de trajet · $0.75 avec TAP Card. 5 min à pied du Bradbury Building.", dur:"20 min" },
      { time:"12h05", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Grand Central Market · 317 S Broadway · food hall historique depuis 1917 · juste en face d'Angels Flight.", dur:"1h" },
      { time:"13h10", type:"activity", label:"🏨 Activité", desc:"Millennium Biltmore Hotel · 506 S Grand Ave · Art Déco 1923 · lobby et Gallery Bar en accès libre · 7 min à pied de Pershing Square.", dur:"30 min" },
      { time:"14h10", type:"transit", label:"🚇 Metro B+A Line", desc:"Pershing Square → Union Station (B Line) → Southwest Museum (A Line) · 25 min total", dur:"$1.75" },
      { time:"14h35", type:"walk", label:"🚶 À pied", desc:"Station Southwest Museum → hôtel Mount Washington · 10 min à pied", dur:"10 min" },
      { time:"14h50", type:"activity", label:"🏃 Activité", desc:"Récupérer voiture. Check-out The Hills Inn Eagle Rock · 2300 Colorado Blvd, Los Angeles CA 90041 (Airbnb · petit déjeuner inclus). Bagages en voiture.", dur:"" },
      { time:"15h00", type:"car", label:"🚗 Voiture", desc:"Mount Washington → Port Hueneme (Oxnard) via CA-134 O + US-101 Nord — 100 km", dur:"1h20" },
      { time:"16h20", type:"activity", label:"🏃 Activité", desc:"Check-in Hotel Oxnard · 1311 Mandalay Beach Road, Oxnard CA 93035 (Airbnb · ⚠️ petit déjeuner NON inclus).", dur:"" },
      { time:"17h00", type:"activity", label:"🏊 Baignade", desc:"Mandalay Beach : plage juste devant l'hébergement. Soirée baignade et détente en famille, coucher de soleil sur le Pacifique.", dur:"2h" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Port Hueneme / Oxnard — restaurants du Channel Islands Harbor.", dur:"1h" },
      { time:"", type:"tip", label:"💡 Courses", desc:"Petit déjeuner NON inclus à l'hébergement — achetez provisions ce soir (Vons/Ralphs à Oxnard) pour les prochains matins.", dur:"30 min" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Solde de 73,80 € restant à payer sur place pour l'hébergement (Airbnb).", dur:"" }
    ]
  },
  { num:"J19", date:"Lun 10 août", title:"Malibu : El Matador (2h plage) · Point Dume · Malibu Pier & Lagoon (aller-retour Port Hueneme)",
    activities:[
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Hotel Oxnard (Port Hueneme) 09h00] — Port Hueneme (Oxnard) → El Matador State Beach (Malibu) via PCH/CA-1 — 50 km", dur:"50 min" },
      { time:"09h50", type:"parking", label:"🅿 Parking", desc:"El Matador State Beach Lot · 32350 Pacific Coast Hwy, Malibu", dur:"$12" },
      { time:"09h55", type:"walk", label:"🏖️ Plage", desc:"El Matador State Beach — la plus belle plage de Malibu : falaises, arches et grottes marines, sable doré. Détente, baignade, exploration des rochers à marée basse. Accès par escalier abrupt.", dur:"2h" },
      { time:"11h55", type:"car", label:"🚗 Voiture", desc:"El Matador → Point Dume State Beach", dur:"15 min" },
      { time:"12h10", type:"parking", label:"🅿 Parking", desc:"Westward Beach Road, Malibu (Point Dume State Beach)", dur:"~$12" },
      { time:"12h15", type:"walk", label:"🚶 À pied", desc:"Point Dume Trail : promontoire rocheux, vue panoramique sur toute la baie de Santa Monica. Observation de baleines possible en saison.", dur:"1h" },
      { time:"13h15", type:"car", label:"🚗 Voiture", desc:"Point Dume → Malibu Country Mart", dur:"15 min" },
      { time:"13h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner — Malibu Country Mart / Cross Creek : restaurants et boutiques chics en plein air.", dur:"1h" },
      { time:"14h30", type:"car", label:"🚗 Voiture", desc:"Malibu Country Mart → Malibu Pier", dur:"10 min" },
      { time:"14h40", type:"parking", label:"🅿 Parking", desc:"Malibu Pier Lot · 25000 Pacific Coast Hwy — parking payant à l'horodateur, pas de réservation. Couvre aussi la Lagoon et Adamson House (2 min à pied).", dur:"$3–4/h" },
      { time:"14h45", type:"walk", label:"🚶 À pied", desc:"Malibu Pier (1905) : jetée historique, pêcheurs, vue sur Surfrider Beach — spot de surf mythique.", dur:"45 min" },
      { time:"15h30", type:"walk", label:"🚶 À pied", desc:"Malibu Lagoon State Beach + Adamson House (tuiles espagnoles peintes à la main) — juste à côté du pier, même parking.", dur:"45 min" },
      { time:"16h15", type:"car", label:"🚗 Voiture", desc:"Malibu Pier → Port Hueneme (Oxnard) via PCH + US-101 Nord — 75 km", dur:"1h" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Port Hueneme / Oxnard.", dur:"1h" }
    ]
  },
  { num:"J20", date:"Mar 11 août", title:"Santa Barbara : Mission · Courthouse · State Street · Stearns Wharf (aller-retour Port Hueneme)",
    activities:[
      { time:"09h00", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Hotel Oxnard (Port Hueneme) 09h00] — Port Hueneme (Oxnard) → Santa Barbara via US-101 Nord — 90 km", dur:"1h" },
      { time:"10h00", type:"parking", label:"🅿 Parking", desc:"Mission Santa Barbara — parking Laguna Street", dur:"Gratuit" },
      { time:"10h05", type:"walk", label:"🚶 À pied", desc:"Mission Santa Barbara (1786) : façade baroque espagnole, jardins et cimetière historique. La plus belle des missions californiennes.", dur:"45 min" },
      { time:"10h50", type:"car", label:"🚗 Voiture", desc:"Mission → Santa Barbara County Courthouse", dur:"10 min" },
      { time:"11h00", type:"walk", label:"🚶 À pied", desc:"Santa Barbara County Courthouse (1929) : architecture espagnole revival, tour de l'horloge El Mirador — vue panoramique gratuite sur la ville et l'océan.", dur:"45 min" },
      { time:"11h45", type:"walk", label:"🚶 À pied", desc:"State Street : boutiques, architecture méditerranéenne, ambiance animée.", dur:"45 min" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Déjeuner — State Street, Santa Barbara.", dur:"1h" },
      { time:"13h30", type:"walk", label:"🚶 À pied", desc:"Stearns Wharf (1872) : jetée historique, restaurants, boutiques, vue sur le port de plaisance.", dur:"45 min" },
      { time:"14h15", type:"walk", label:"🚶 À pied", desc:"Santa Barbara Harbor : bateaux de pêche, otaries, promenade du front de mer.", dur:"30 min" },
      { time:"14h45", type:"car", label:"🚗 Voiture", desc:"Harbor → East Beach", dur:"10 min" },
      { time:"15h00", type:"walk", label:"🚶 À pied", desc:"East Beach : plage principale de Santa Barbara, vue sur les Channel Islands. Temps libre.", dur:"2h" },
      { time:"17h30", type:"car", label:"🚗 Voiture", desc:"East Beach → Port Hueneme (Oxnard) via US-101 Sud — 90 km", dur:"1h" },
      { time:"18h30", type:"activity", label:"🧺 Lessive", desc:"Lessive à l'hébergement (lave-linge sur place).", dur:"1h30" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Port Hueneme / Oxnard.", dur:"1h" }
    ]
  },
  { num:"J21", date:"Mer 12 août", title:"Port Hueneme → Piedras Blancas → Hearst Castle → Morro Bay",
    activities:[
      { time:"08h15", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Hotel Oxnard (Port Hueneme) 08h15] — Port Hueneme (Oxnard) → Piedras Blancas (San Simeon) via US-101 + CA-1 — 290 km", dur:"3h15" },
      { time:"11h30", type:"parking", label:"🅿 Parking", desc:"Piedras Blancas Rookery Lot · CA-1, San Simeon CA 93452", dur:"Gratuit" },
      { time:"13h30", type:"car", label:"🚗 Voiture", desc:"Piedras Blancas → Hearst Castle Visitor Center — 15 min", dur:"15 min" },
      { time:"13h50", type:"transit", label:"🚌 Navette obligatoire", desc:"Visitor center → château (accès voiture impossible). Navette incluse.", dur:"5 min" },
      { time:"14h00", type:"walk", label:"🚶 À pied", desc:"Hearst Castle — Grand Rooms Tour 1h30 : piscine Neptune, art européen, collections pharaoniques.", dur:"1h30" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Réservation obligatoire sur hearstcastle.org — créneaux partent vite en été.", dur:"" },
      { time:"15h45", type:"car", label:"🚗 Voiture", desc:"Hearst Castle → Morro Bay via CA-1 Sud — 25 min", dur:"25 min" },
      { time:"16h15", type:"activity", label:"🏃 Activité", desc:"Check-in The Sea Air Inn & Suites · 845 Morro Avenue, Morro Bay CA 93442 (⚠️ hôtel de remplacement — l'hébergement Cambria initial a été annulé).", dur:"" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Morro Bay en ville — vue sur Morro Rock.", dur:"1h" }
    ]
  },
  { num:"J22", date:"Jeu 13 août", title:"Morro Bay → Big Sur (McWay Falls · Partington Cove · Bixby Bridge) → Monterey",
    activities:[
      { time:"08h45", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel The Sea Air Inn & Suites (Morro Bay) 08h45] — Morro Bay → McWay Falls (Julia Pfeiffer Burns SP) via Hwy 1 — 1h15", dur:"1h15" },
      { time:"10h00", type:"parking", label:"🅿 Parking", desc:"McWay Falls Lot · Hwy 1, Julia Pfeiffer Burns SP", dur:"Gratuit (pass)" },
      { time:"10h05", type:"walk", label:"🚶 À pied", desc:"McWay Falls : cascade tombant directement sur la plage. Sentier 300m A/R.", dur:"20 min" },
      { time:"10h30", type:"car", label:"🚗 Voiture", desc:"McWay Falls → Partington Cove — 15 min", dur:"15 min" },
      { time:"10h50", type:"walk", label:"🚶 À pied", desc:"Partington Cove Trail : 1,5 km A/R · tunnel taillé dans la falaise vers une crique secrète.", dur:"1h30" },
      { time:"12h30", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Nepenthe Restaurant : terrasse à 244m sur le Pacifique. Vue légendaire sur Big Sur.", dur:"1h" },
      { time:"13h35", type:"car", label:"🚗 Voiture", desc:"Nepenthe → Bixby Creek Bridge — 20 min", dur:"20 min" },
      { time:"14h00", type:"walk", label:"🚶 À pied", desc:"Bixby Creek Bridge : pont emblématique de la Hwy 1. Photo depuis le bas-côté nord du pont.", dur:"15 min" },
      { time:"14h20", type:"car", label:"🚗 Voiture", desc:"Bixby → Point Sur — 10 min", dur:"10 min" },
      { time:"14h50", type:"car", label:"🚗 Voiture", desc:"Point Sur → Garrapata SP via arrêts bas-côtés : Hurricane Point, Soberanes Point (5 min chacun)", dur:"25 min" },
      { time:"15h15", type:"parking", label:"🅿 Parking", desc:"Garrapata State Park Lot · Hwy 1", dur:"Gratuit" },
      { time:"15h20", type:"walk", label:"🚶 À pied", desc:"Garrapata State Park : sentier côtier 2–3 km · falaises spectaculaires sur le Pacifique.", dur:"1h" },
      { time:"16h25", type:"car", label:"🚗 Voiture", desc:"Garrapata → Cannery Row (Monterey) — 30 min", dur:"30 min" },
      { time:"19h00", type:"meal", label:"🍽️ Dîner", desc:"Dîner Cannery Row — Monterey.", dur:"1h" },
      { time:"20h00", type:"car", label:"🚗 Voiture", desc:"Monterey → Santa Cruz via Hwy 1 Nord — 70 km", dur:"1h05" },
      { time:"21h05", type:"activity", label:"🏃 Activité", desc:"Check-in Aqua Breeze Inn · Santa Cruz (Airbnb/Booking).", dur:"" }
    ]
  },
  { num:"J23", date:"Ven 14 août", title:"Point Lobos (matin) + Sortie Baleines 13h30 · Carmel village",
    activities:[
      { time:"07h30", type:"car", label:"🚗 Voiture", desc:"🏨 [Départ hôtel Aqua Breeze Inn (Santa Cruz) 07h30] — Santa Cruz → Point Lobos State Natural Reserve via Hwy 1 Sud — 80 km", dur:"1h15" },
      { time:"08h45", type:"parking", label:"🅿 Parking", desc:"Point Lobos Entrance Lot · 62 CA-1, Carmel-by-the-Sea CA 93923", dur:"$10" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"PAS de réservation en ligne (Point Lobos n'est pas sur ReserveCalifornia ; le futur système ParkIT! n'est pas encore lancé) — entrée 10 $/véhicule payable sur place, premier arrivé premier servi. Parking limité (~150 places), ferme dès qu'il est complet en été et rouvre au fil des départs — arrivez avant 9h pour être sûrs d'entrer.", dur:"" },
      { time:"08h50", type:"walk", label:"🚶 À pied", desc:"Point Lobos State Natural Reserve : loutres de mer, phoques, lions de mer, cyprès centenaires. Cypress Grove Trail (2 km) + Bird Island Trail. Visite tranquille, sans être pressés par le bateau.", dur:"1h45" },
      { time:"10h35", type:"car", label:"🚗 Voiture", desc:"Point Lobos → Fisherman's Wharf (Monterey)", dur:"20 min" },
      { time:"10h55", type:"parking", label:"🅿 Parking", desc:"Fisherman's Wharf Lot · 99 Pacific St, Monterey CA 93940", dur:"$3–4/h" },
      { time:"11h00", type:"meal", label:"🍽️ Déjeuner", desc:"Pause déjeuner — Cannery Row : fruits de mer, ambiance Steinbeck.", dur:"1h30" },
      { time:"13h30", type:"boat", label:"⛴ Bateau", desc:"Sortie baleines Monterey Bay Whale Watch (3h) : baleines à bosse, dauphins, loutres. Créneau après-midi d'été (13h30).", dur:"3h · ~$60/pers" },
      { time:"16h30", type:"car", label:"🚗 Voiture", desc:"Fisherman's Wharf → Carmel-by-the-Sea", dur:"15 min" },
      { time:"16h45", type:"parking", label:"🅿 Parking", desc:"Parking municipal Carmel · Junipero St & 3rd Ave", dur:"Gratuit 2h" },
      { time:"16h50", type:"walk", label:"🚶 À pied", desc:"Carmel-by-the-Sea : village sans numéros de rues · boutiques d'art · galeries · Ocean Avenue jusqu'à la plage (sable blanc, eau turquoise).", dur:"1h" },
      { time:"17h50", type:"car", label:"🚗 Voiture", desc:"Carmel → Santa Cruz via Hwy 1 Nord — 80 km", dur:"1h15" },
      { time:"19h30", type:"meal", label:"🍽️ Dîner", desc:"Dîner Santa Cruz — Municipal Wharf ou West Cliff Drive.", dur:"1h" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"Sortie baleines à 13h30 (créneau après-midi d'été) plutôt qu'à 9h/10h — vérifiez l'horaire exact sur montereybaywhalewatch.com/schedule avant de partir (peut varier selon le jour). 17-Mile Drive, Mission Ranch et Aquarium Monterey retirés faute de temps. Préparez les bagages ce soir — départ 8h30 demain pour SFO via Silicon Valley.", dur:"" }
    ]
  },
  { num:"J24", date:"Sam 15 août", title:"Stanford · Google · Meta (photo) · Apple Park → SFO · Vol 16h05",
    activities:[
      { time:"08h30", type:"activity", label:"🏃 Activité", desc:"🏨 [Départ hôtel Aqua Breeze Inn (Santa Cruz) 08h30] — Check-out hôtel Santa Cruz. Bagages en voiture. Départ 8h30 au plus tard.", dur:"" },
      { time:"08h30", type:"car", label:"🚗 Voiture", desc:"Santa Cruz → Stanford University (Palo Alto) via Hwy 17 N + I-280 N — 65 km", dur:"1h" },
      { time:"09h30", type:"parking", label:"🅿 Parking", desc:"Stanford University · Palm Drive, Palo Alto CA 94305", dur:"Gratuit w-e · $3/h semaine" },
      { time:"09h35", type:"walk", label:"🚶 À pied", desc:"Stanford University : Memorial Church (néo-roman doré), Hoover Tower, Inner Quad. Campus de 3300 ha.", dur:"45 min" },
      { time:"10h25", type:"car", label:"🚗 Voiture", desc:"Stanford → Google Visitor Experience (Mountain View) via US-101 N — 15 min", dur:"15 min" },
      { time:"10h40", type:"parking", label:"🅿 Parking", desc:"Alta Garage · 1001 Alta Ave, Mountain View CA 94043", dur:"Gratuit · ~8 min à pied du Visitor Experience" },
      { time:"10h50", type:"walk", label:"🚶 À pied", desc:"Google Visitor Experience — Gradient Canopy (2000 N Shoreline Blvd) : Google Store, café, art installations, plaza extérieure. Vue sur le Googleplex. T-rex géant. Accès libre sans réservation.", dur:"30 min" },
      { time:"", type:"tip", label:"💡 Conseil", desc:"L'intérieur du Googleplex est réservé aux employés. Le Visitor Experience au Gradient Canopy est la vraie attraction publique.", dur:"" },
      { time:"11h25", type:"car", label:"🚗 Voiture", desc:"Google → Meta Headquarters (Menlo Park) via US-101 N — 10 min", dur:"10 min" },
      { time:"11h35", type:"parking", label:"🅿 Parking", desc:"Rue Chilco Street, Menlo Park", dur:"Gratuit · quelques places" },
      { time:"11h40", type:"walk", label:"🚶 À pied", desc:"Meta Headquarters — 1 Meta Way (ex 1 Hacker Way), Menlo Park : photo du panneau Meta depuis la rue. Campus fermé au public sans invitation d'un employé.", dur:"15 min" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Si vous manquez de temps, supprimez Meta (photo depuis la rue uniquement) pour gagner 25 min précieuses avant SFO.", dur:"" },
      { time:"12h00", type:"car", label:"🚗 Voiture", desc:"Meta → Apple Park Visitor Center (Cupertino) via US-101 S + I-280 N — 15 min", dur:"15 min" },
      { time:"12h15", type:"parking", label:"🅿 Parking", desc:"Apple Park Visitor Center · 1 Apple Park Way, Cupertino CA 95014", dur:"Gratuit · parking sur site" },
      { time:"12h20", type:"walk", label:"🚶 À pied", desc:"Apple Park Visitor Center : terrasse avec vue sur l'anneau de verre, maquette en réalité augmentée, Apple Store exclusif. Entrée libre.", dur:"30 min" },
      { time:"12h55", type:"car", label:"🚗 Voiture", desc:"Apple Park → SFO via I-280 N + US-101 N — 35 km", dur:"30 min" },
      { time:"13h25", type:"activity", label:"🏃 Activité", desc:"Arrivée SFO. Restitution voiture de location — retour véhicule + navette terminal : prévoir 45 min minimum.", dur:"45 min" },
      { time:"14h10", type:"activity", label:"🏃 Activité", desc:"Enregistrement + sécurité SFO. Prévoir 1h30 minimum pour l'international en haute saison.", dur:"" },
      { time:"16h05", type:"activity", label:"🏃 Activité", desc:"✈️ DÉCOLLAGE SFO → Paris Orly. Bon voyage !", dur:"" },
      { time:"", type:"alert", label:"⚠️ Alerte", desc:"Timing serré ce dernier jour — partez de Santa Cruz à 8h30 impérativement. En cas de retard, supprimez Meta pour gagner 25 min.", dur:"" }
    ]
  }
];



/* ==============================================================
   Étapes (tableau récapitulatif) — v14 (prix + plateformes ajoutés)
   ============================================================== */
const ETAPES = [
  { num:1,  icon:"🌉", name:"San Francisco",           dayIdx:0,  nuits:3, dates:"Jeu 23 – Dim 26 juil",
    sites:"Pier 39, vélo Golden Gate + Sausalito (ferry), Lombard St, Filbert St, Chinatown, Painted Ladies, Battery Spencer, Twin Peaks, Coit Tower, Ferry Building, Haight-Ashbury, Castro, Columbia State Historic Park",
    hotelEnc:"NfPYr8AaSxP69tHL:I5FXsEqD7OVScHT4r+JVRrPDdBqCe2C8O7agCNpeap69Cgrxk1tawzSnXy0nTBOjqt+H8YyhxPvjE8kd+/NrFqFIPoTiY72AdbYuZYu3Hyc=" },
  { special:true, icon:"🛎️", name:"Conciergerie", dates:"Dim 26 juil", desc:"Check out : 1h · Vérification Ménage : 4h à 6h · Check in : à partir de 7h - Kelly" },
  { num:2,  icon:"🏔️", name:"Yosemite West",           dayIdx:3,  nuits:3, dates:"Dim 26 – Mer 29 juil",
    sites:"Glacier Point (2200m), Mist Trail (Vernal Fall 97m + Nevada Fall 180m), Yosemite Falls (739m · 11km), Mirror Lake, Olmsted Point, Tenaya Lake (2484m), Tuolumne Meadows, Mariposa Grove (Grizzly Giant 2700 ans)",
    hotelEnc:"n/O85Aq44AmvhFrW:MaR8EonxsOOyu0sxFM7+IoVgA0MkKl5TCacfxReg7ExEt3PWSy1mOgYE6jL9T4KgAEfGEKvMIAjlSX90Pca/KQFAh604GnudsMTdmQqmboSHMUzXwVZ4yww4t9Qb2vE=" },
  { num:3,  icon:"🌲", name:"Kings Canyon NP",          dayIdx:6,  nuits:1, dates:"Mer 29 – Jeu 30 juil",
    sites:"Zumwalt Meadow Trail, Kings Canyon Scenic Byway, Junction View, Grizzly Falls, Roaring River Falls",
    hotelEnc:"l8PDm91pSCYcc/U7:SyaU+GOMBhpEokq+LRp4DT7fgx5vDzWe37VNqlYfbOkdcV8clmebrVARoIwIRSdRaDoJ4+YOOrBLMcOCP4PlEOQTnl0U1WjXPuHfOR8DEWP84xfnb5tw509dWB62+FGircwWmw==" },
  { num:4,  icon:"🌳", name:"Sequoia NP / Lemon Cove",  dayIdx:7,  nuits:1, dates:"Jeu 30 – Ven 31 juil",
    sites:"General Sherman Tree (plus grand arbre du monde), Big Tree Trail, Tunnel Log, Moro Rock (300 marches)",
    hotelEnc:"RIAiOl5CKPAT59Wo:rl2bVpahJa+H30b9bu/9ZB55QgVtqdUnCtW0taezYdysMvk8o5UEC5t8wPslVH3tmoWaHPWZvlqJOVlhFhXA9KHxJkmI10Xrq3m9iJ6nLxdj/oMxMJbRZDo=" },
  { num:5,  icon:"🏜️", name:"Death Valley",             dayIdx:8,  nuits:1, dates:"Ven 31 juil – Sam 1er août",
    sites:"Dante's View (1669m), Zabriskie Point, Mesquite Flat Dunes (lever de soleil), Badwater Basin (-86m), Artist Drive",
    hotelEnc:"fCs32jEkT1gArkkw:u+do0KQr7DHCMy2PweNvMqqfRwsFuQnbp5suu6hBu4FCXN4Cu545QO0CU8xwKIwoaj4sNAFQMuTK1cQbGkrzKV+GSFhozjOougP6DcZoQcoss7UGWrPxsg==" },
  { special:true, icon:"🛎️", name:"Conciergerie", dates:"Sam 1er août", desc:"Check out : 1h · Vérification Ménage : 4h à 6h · Check in : à partir de 7h - Mélanie" },
  { num:6,  icon:"🎰", name:"Las Vegas",                dayIdx:9,  nuits:1, dates:"Sam 1 – Dim 2 août",
    sites:"Fremont Street Experience (plafond LED 460m), The Strip by night, fontaines Bellagio, Caesar's Palace",
    hotelEnc:"I6SlQxVN6bFxRwYN:pHV75mLS0Qpwe0SwtPUgTpKlkqMXiVULMqKQAN4vnWL130Iwg9F1uaegNa9ghW+xMrv7YflwNM+01zb0EonA3Fsfhjdi39GZrGzjp2ApeRLaea9BXEW9B29jFVqtqHd3" },
  { num:7,  icon:"🏜️", name:"Grand Canyon West / Williams", dayIdx:10, nuits:1, dates:"Dim 2 – Lun 3 août",
    sites:"Grand Canyon West (Hualapai Reservation) : Skywalk, Eagle Point, Native American Village, Guano Point, Hualapai Ranch",
    hotelEnc:"/5a7nGUK/qq95hyG:OLKPuaoTj5c137w1fTxZSvoGPMaT4HJGFI7I4zEW5mhHEvnHldOifXCARE3TLz3gahbTG2ybVwJt612kTF8Nkr4+oZJ5E55MqXgOeYApR2ibdBz9rdy5AI92/3bVTx+u34m9F0FU" },
  { num:8,  icon:"🌵", name:"Grand Canyon South Rim / Joshua Tree / Palm Springs", dayIdx:11, nuits:2, dates:"Lun 3 – Mer 5 août",
    sites:"Grand Canyon South Rim : Mather Point, Rim Trail (Hopi Point, Hermits Rest) · Hidden Valley, Cap Rock, Keys View (1581m), Cholla Cactus Garden, Skull Rock · Aerial Tramway (2600m), Palm Canyon Drive, Marilyn Forever, Graffiti Yard",
    hotelEnc:"6QuUJdBjFGjic4wL:fd0teJzIw+mPE1Hhnm0nzXWKVRTj/YnVDoTxlKamkK5rCA+ajrq28AxGDO2qUTqbOCJh8xPiOJ1ENEaorr9PWqTTOoVFTbHt62RwEzb2Z99mnyuLTWndcGs6MP9mVGKD2HiSi0m8" },
  { num:9,  icon:"🎬", name:"Los Angeles (Santa Monica)", dayIdx:13, nuits:3, dates:"Mer 5 – Sam 8 août",
    sites:"Cimetière Westwood, Château Marmont, Venice Beach, Venice Canaux, Abbot Kinney, Santa Monica Pier, Griffith Observatory, Hollywood Sign, Hollyhock House, Walk of Fame, Universal Studios",
    hotelEnc:"cpevapN2SHRNTxBe:vXevvDGWJdxP5O1DhNJ7v1xBpzx53gTFY3nEaRQ0M4Q16MCoLR3/C70JUDvAsNHeyRtkNYH6A6qpvH7r8Oz2d4rqks6AJwE+/cXMQHrPlZXgaG47j6QUWGk8XTd7aA==" },
  { special:true, icon:"🛎️", name:"Conciergerie", dates:"Sam 8 août", desc:"Check out : 1h · Vérification Ménage : 4h à 6h · Check in : à partir de 7h - Dominique" },
  { num:10, icon:"🎬", name:"Los Angeles (Eagle Rock)",  dayIdx:16, nuits:1, dates:"Sam 8 – Dim 9 août",
    sites:"Mulholland Drive, Runyon Canyon, Beachwood Canyon, Melrose, Spadena House, Rodeo Drive, Highland Park, Downtown LA, Bradbury Building, Grand Central Market, Malibu Point Dume",
    hotelEnc:"aNpwfWMBk2rWIDgp:w0SVGAFhKZCsFdWNH+wuvThOzamcx+VVj04g6TLnkciYzsuWVuREbC/XlA/rIP6aAIi1AFIsx6mfTrl25wMThmpxBBrKx4zQkGTrk3IGynOdfqmP+bENSN/NWLKW0zluXTZrzEnv18lXDVcR" },
  { num:11, icon:"🏖️", name:"Port Hueneme / Oxnard",     dayIdx:17, nuits:3, dates:"Dim 9 – Mer 12 août",
    sites:"Baignade Mandalay Beach · Malibu (El Matador, Point Dume, Malibu Pier, Getty Villa) · Santa Barbara (Mission, Courthouse, State Street, Stearns Wharf)",
    hotelEnc:"+oQ5xEckd6bYfpxk:+SiUuSSVaHbq0UlTx1qnck8aUuI7q3J/1OxusmqVJMJJjxLNK9zUDaRXAlsZuSxIknHO8wv85fP/uFs9LHTiUoaGVrnfXfKWjO5NhiwKUiTq8Qgwa+y8EJoaktWR3w4YrnMmYxI3HV2Mt/Ih5maPqtXQModD29QuTiX2GGFRbG8=" },
  { num:12, icon:"🐘", name:"Morro Bay",                 dayIdx:20, nuits:1, dates:"Mer 12 – Jeu 13 août",
    sites:"Piedras Blancas (éléphants de mer), Hearst Castle (Grand Rooms Tour), Morro Rock",
    hotelEnc:"QlIBXNaMp8mrWg6j:oGga0b2yJ5fbNKaOEOxSYK7+DQD8f/yiJHRfWLxA9K8G" },
  { num:13, icon:"🐋", name:"Monterey / Carmel (base Santa Cruz)", dayIdx:21, nuits:2, dates:"Jeu 13 – Sam 15 août",
    sites:"Big Sur Hwy 1 : McWay Falls, Partington Cove (tunnel falaise), Bixby Bridge, Point Sur, Garrapata SP · Point Lobos · Sortie baleines (3h) · Carmel village",
    hotelEnc:"UtBJe7o+L8F07uvt:Ux5yUdHu4i6npZ8oxkd4rLYHzflf6cfimvzdF1/4HZD3EJMxlXihhedvu1Od9TqIwxUYFgIFG6u40wGHu641J6fWE9FrQE/2VwwriA5xos4pdQvt7Sc84BgthCr6hELZOQiRvYjJA4A=" },
  { num:14, icon:"💻", name:"Silicon Valley / SFO",     dayIdx:23, nuits:0, dates:"Sam 15 août (départ)",
    sites:"Stanford University, Google Visitor Experience (Gradient Canopy), Meta HQ (photo), Apple Park Visitor Center → SFO · Vol 16h05",
    hotelEnc:"Qam4NebQ9XNi1Rho:JrZ5slylyukiY6eQnTNIaL+8y/EUBII0/+tOsKHt5Hwy" },
  { special:true, icon:"🛎️", name:"Conciergerie", dates:"Dim 16 août", desc:"Check out : 1h · Vérification Ménage : 4h à 6h · Check in : à partir de 7h - Julie" }
];